app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, PasswordField
from wtforms.validators import DataRequired, EqualTo, Length


class Login(FlaskForm):
    account = StringField(u'账号', validators=[DataRequired()])
    password = PasswordField(u'密码', validators=[DataRequired()])
    submit = SubmitField(u'登录')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField(u'原密码', validators=[DataRequired()])
    password = PasswordField(u'新密码', validators=[DataRequired(), EqualTo('password2', message=u'两次密码必须一致！')])
    password2 = PasswordField(u'确认新密码', validators=[DataRequired()])
    submit = SubmitField(u'确认修改')


class EditInfoForm(FlaskForm):
    name = StringField(u'用户名', validators=[Length(1, 32)])
    submit = SubmitField(u'提交')


class SearchBookForm(FlaskForm):
    methods = [('book_name', '书名'), ('author', '作者'), ('class_name', '类别'), ('isbn', 'ISBN')]
    method = SelectField(choices=methods, validators=[DataRequired()], coerce=str)
    content = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class SearchStudentForm(FlaskForm):
    card = StringField(validators=[DataRequired()])
    submit = SubmitField('搜索')


class StoreForm(FlaskForm):
    barcode = StringField(validators=[DataRequired(), Length(6)])
    isbn = StringField(validators=[DataRequired(), Length(13)])
    location = StringField(validators=[DataRequired(), Length(1, 32)])
    submit = SubmitField(u'提交')


class NewStoreForm(FlaskForm):
    isbn = StringField(validators=[DataRequired(), Length(13)])
    book_name = StringField(validators=[DataRequired(), Length(1, 64)])
    press = StringField(validators=[DataRequired(), Length(1, 32)])
    author = StringField(validators=[DataRequired(), Length(1, 64)])
    class_name = StringField(validators=[DataRequired(), Length(1, 64)])
    submit = SubmitField(u'提交')


class BorrowForm(FlaskForm):
    card = StringField(validators=[DataRequired()])
    book_name = StringField(validators=[DataRequired()])
    submit = SubmitField(u'搜索')

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)

from . import views  # 咱没有自定义错误页面

app/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, flash, request, jsonify
from flask_login import login_user, logout_user, login_required, current_user
from . import main
from .forms import Login, SearchBookForm, ChangePasswordForm, EditInfoForm, SearchStudentForm, NewStoreForm, StoreForm, BorrowForm
from .. import db
from ..models import Admin, Book, Inventory, Student, ReadBook
import time, datetime


@main.route('/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        user = Admin.query.filter_by(admin_id=form.account.data, password=form.password.data).first()
        if user is None:
            flash('账号或密码错误！')
            return redirect(url_for('.login'))
        else:
            login_user(user)
            session['admin_id'] = user.admin_id
            session['name'] = user.admin_name
            return redirect(url_for('.index'))
    return render_template('main/login.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已经登出！')
    return redirect(url_for('.login'))


@main.route('/index')
@login_required
def index():
    return render_template('main/index.html', name=session.get('name'))


@main.route('/echarts')
@login_required
def echarts():
    days = []
    num = []
    today_date = datetime.date.today()
    today_str = today_date.strftime("%Y-%m-%d")
    today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
    ten_ago = int(today_stamp) - 9 * 86400
    for i in range(0, 10):
        borr = ReadBook.query.filter_by(start_date=str((ten_ago+i*86400)*1000)).count()
        retu = ReadBook.query.filter_by(end_date=str((ten_ago+i*86400)*1000)).count()
        num.append(borr + retu)
        days.append(timeStamp((ten_ago+i*86400)*1000))
    data = []
    for i in range(0, 10):
        item = {'name': days[i], 'num': num[i]}
        data.append(item)
    return jsonify(data)


@main.route('/user/<id>')
@login_required
def user_info(id):
    user = Admin.query.filter_by(admin_id=id).first()
    return render_template('main/user-info.html', user=user, name=session.get('name'))


@main.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.password2.data != form.password.data:
        flash(u'两次密码不一致！')
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            db.session.commit()
            flash(u'已成功修改密码！')
            return redirect(url_for('.index'))
        else:
            flash(u'原密码输入错误，修改失败！')
    return render_template("main/change-password.html", form=form)


@main.route('/change_info', methods=['GET', 'POST'])
@login_required
def change_info():
    form = EditInfoForm()
    if form.validate_on_submit():
        current_user.admin_name = form.name.data
        db.session.add(current_user)
        flash(u'已成功修改个人信息！')
        return redirect(url_for('.user_info', id=current_user.admin_id))
    form.name.data = current_user.admin_name
    id = current_user.admin_id
    right = current_user.right
    return render_template('main/change-info.html', form=form, id=id, right=right)


@main.route('/search_book', methods=['GET', 'POST'])
@login_required
def search_book():  # 这个函数里不再处理提交按钮，使用Ajax局部刷新
    form = SearchBookForm()
    return render_template('main/search-book.html', name=session.get('name'), form=form)


@main.route('/books', methods=['POST'])
def find_book():

    def find_name():
        return Book.query.filter(Book.book_name.like('%'+request.form.get('content')+'%')).all()

    def find_author():
        return Book.query.filter(Book.author.contains(request.form.get('content'))).all()

    def find_class():
        return Book.query.filter(Book.class_name.contains(request.form.get('content'))).all()

    def find_isbn():
        return Book.query.filter(Book.isbn.contains(request.form.get('content'))).all()

    methods = {
        'book_name': find_name,
        'author': find_author,
        'class_name': find_class,
        'isbn': find_isbn
    }
    books = methods[request.form.get('method')]()
    data = []
    for book in books:
        count = Inventory.query.filter_by(isbn=book.isbn).count()
        available = Inventory.query.filter_by(isbn=book.isbn, status=True).count()
        item = {'isbn': book.isbn, 'book_name': book.book_name, 'press': book.press, 'author': book.author,
                'class_name': book.class_name, 'count': count, 'available': available}
        data.append(item)
    return jsonify(data)


@main.route('/user/book', methods=['GET', 'POST'])
def user_book():
    form = SearchBookForm()
    return render_template('main/user-book.html', form=form)


@main.route('/search_student', methods=['GET', 'POST'])
@login_required
def search_student():
    form = SearchStudentForm()
    return render_template('main/search-student.html', name=session.get('name'), form=form)


def timeStamp(timeNum):
    if timeNum is None:
        return timeNum
    else:
        timeStamp = float(float(timeNum)/1000)
        timeArray = time.localtime(timeStamp)
        print(time.strftime("%Y-%m-%d", timeArray))
        return time.strftime("%Y-%m-%d", timeArray)


@main.route('/student', methods=['POST'])
def find_student():
    stu = Student.query.filter_by(card_id=request.form.get('card')).first()
    if stu is None:
        return jsonify([])
    else:
        valid_date = timeStamp(stu.valid_date)
        return jsonify([{'name': stu.student_name, 'gender': stu.sex, 'valid_date': valid_date, 'debt': stu.debt}])


@main.route('/record', methods=['POST'])
def find_record():
    records = db.session.query(ReadBook).join(Inventory).join(Book).filter(ReadBook.card_id == request.form.get('card'))\
        .with_entities(ReadBook.barcode, Inventory.isbn, Book.book_name, Book.author, ReadBook.start_date,
                       ReadBook.end_date, ReadBook.due_date).all()  # with_entities啊啊啊啊卡了好久啊
    data = []
    for record in records:
        start_date = timeStamp(record.start_date)
        due_date = timeStamp(record.due_date)
        end_date = timeStamp(record.end_date)
        if end_date is None:
            end_date = '未归还'
        item = {'barcode': record.barcode, 'book_name': record.book_name, 'author': record.author,
                'start_date': start_date, 'due_date': due_date, 'end_date': end_date}
        data.append(item)
    return jsonify(data)


@main.route('/user/student', methods=['GET', 'POST'])
def user_student():
    form = SearchStudentForm()
    return render_template('main/user-student.html', form=form)


@main.route('/storage', methods=['GET', 'POST'])
@login_required
def storage():
    form = StoreForm()
    if form.validate_on_submit():
        book = Book.query.filter_by(isbn=request.form.get('isbn')).first()
        exist = Inventory.query.filter_by(barcode=request.form.get('barcode')).first()
        if book is None:
            flash(u'添加失败，请注意本书信息是否已录入，若未登记，请在‘新书入库’窗口录入信息。')
        else:
            if len(request.form.get('barcode')) != 6:
                flash(u'图书编码长度错误')
            else:
                if exist is not None:
                    flash(u'该编号已经存在！')
                else:
                    item = Inventory()
                    item.barcode = request.form.get('barcode')
                    item.isbn = request.form.get('isbn')
                    item.admin = current_user.admin_id
                    item.location = request.form.get('location')
                    item.status = True
                    item.withdraw = False
                    today_date = datetime.date.today()
                    today_str = today_date.strftime("%Y-%m-%d")
                    today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
                    item.storage_date = int(today_stamp)*1000
                    db.session.add(item)
                    db.session.commit()
                    flash(u'入库成功！')
        return redirect(url_for('.storage'))
    return render_template('main/storage.html', name=session.get('name'), form=form)


@main.route('/new_store', methods=['GET', 'POST'])
@login_required
def new_store():
    form = NewStoreForm()
    if form.validate_on_submit():
        if len(request.form.get('isbn')) != 13:
            flash(u'ISBN长度错误')
        else:
            exist = Book.query.filter_by(isbn=request.form.get('isbn')).first()
            if exist is not None:
                flash(u'该图书信息已经存在，请核对后再录入；或者填写入库表。')
            else:
                book = Book()
                book.isbn = request.form.get('isbn')
                book.book_name = request.form.get('book_name')
                book.press = request.form.get('press')
                book.author = request.form.get('author')
                book.class_name = request.form.get('class_name')
                db.session.add(book)
                db.session.commit()
                flash(u'图书信息添加成功！')
        return redirect(url_for('.new_store'))
    return render_template('main/new-store.html', name=session.get('name'), form=form)


@main.route('/borrow', methods=['GET', 'POST'])
@login_required
def borrow():
    form = BorrowForm()
    return render_template('main/borrow.html', name=session.get('name'), form=form)


@main.route('/find_stu_book', methods=['GET', 'POST'])
def find_stu_book():
    stu = Student.query.filter_by(card_id=request.form.get('card')).first()
    today_date = datetime.date.today()
    today_str = today_date.strftime("%Y-%m-%d")
    today_stamp = time.mktime(time.strptime(today_str + ' 00:00:00', '%Y-%m-%d %H:%M:%S'))
    if stu is None:
        return jsonify([{'stu': 0}])  # 没找到
    if stu.debt is True:
        return jsonify([{'stu': 1}])  # 欠费
    if int(stu.valid_date) < int(today_stamp)*1000:

app/templates/main/base-user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../static/layui/css/layui.css">
    <link rel="stylesheet" href="../static/login.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <style>
          .alert{position:relative;padding:.75rem 1.25rem;margin-bottom:1rem;border:1px solid transparent;border-radius:.25rem}
          .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
          .alert-warning{color:#856404;background-color:#fff3cd;border-color:#ffeeba}
          .close{float:right;font-size:1.5rem;font-weight:700;line-height:1;color:#000;text-shadow:0 1px 0 #fff;opacity:.5}
          .close:focus,.close:hover{color:#000;text-decoration:none;opacity:.75}
          .close:not(:disabled):not(.disabled){cursor:pointer}
          button.close{padding:0;background-color:transparent;border:0;-webkit-appearance:none}
          .close{padding:1rem;margin:-1rem -1rem -1rem auto}
          .alert-dismissible .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
    </style>
</head>
<body>
<div class="layui-layout layui-layout-admin">
<div class="layui-header layui-bg-cyan">
  <div class="layui-logo"><span style="color:#F0F0F0;font-size: large">图书管理系统</span></div>
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.login') }}">登录</a></li>
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.user_student') }}">学生信息查询</a></li>
      <li class="layui-nav-item"><a class="aa" href="{{ url_for('main.user_book') }}">图书信息查询</a></li>
    </ul>
  </div>
</div>
{% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
    </div>
{% endfor %}
</div>

{% block body %}
{% endblock %}

<script src="../static/layui/layui.js"></script>
<script type="text/javascript">
    layui.use('form', function () {
        var form = layui.form;

    });
</script>
{% block script %}{% endblock %}
</body>
</html>

app/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="../static/layui/css/layui.css">
  <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
      .alert{position:relative;padding:.75rem 1.25rem;margin-bottom:1rem;border:1px solid transparent;border-radius:.25rem}
      .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
      .alert-warning{color:#856404;background-color:#fff3cd;border-color:#ffeeba}
      .close{float:right;font-size:1.5rem;font-weight:700;line-height:1;color:#000;text-shadow:0 1px 0 #fff;opacity:.5}
      .close:focus,.close:hover{color:#000;text-decoration:none;opacity:.75}
      .close:not(:disabled):not(.disabled){cursor:pointer}
      button.close{padding:0;background-color:transparent;border:0;-webkit-appearance:none}
      .close{padding:1rem;margin:-1rem -1rem -1rem auto}
      .alert-dismissible .close{position:absolute;top:0;right:0;padding:.75rem 1.25rem;color:inherit}
  </style>
  {% block head %}{% endblock %}
  <style>{% block style %}{% endblock %}</style>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <a href="{{ url_for('main.index') }}"><div class="layui-logo">图书管理系统</div></a>
    <!-- 头部区域（可配合layui已有的水平导航） -->
    <ul class="layui-nav layui-layout-right">
      <li class="layui-nav-item">
        <a href="javascript:;">
          <img src="../static/icon.jpg" class="layui-nav-img">
          {{ name }}
        </a>
        <dl class="layui-nav-child">
          <dd><a href="{{ url_for('main.user_info', id=current_user.admin_id) }}">个人信息</a></dd>
          <dd><a href="{{ url_for('main.change_password') }}">修改密码</a></dd>
        </dl>
      </li>
      <li class="layui-nav-item"><a href="{{ url_for('main.logout') }}">退出登录</a></li>
    </ul>
  </div>

  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree"  lay-filter="test">
        <li class="layui-nav-item">
          <a class="" href="javascript:;">图书管理</a>
          <dl class="layui-nav-child">
             <dd><a href="{{ url_for('main.storage') }}">入库管理</a></dd>
             <dd><a href="{{ url_for('main.borrow') }}">学生借书</a></dd>
             <dd><a href="{{ url_for('main.return_book') }}">学生还书</a></dd>
             <dd><a href="javascript:;">图书注销</a></dd>
           </dl>
        </li>
        <li class="layui-nav-item">
          <a href="javascript:;">信息设置</a>
          <dl class="layui-nav-child">
             <dd><a href="{{ url_for('main.change_info') }}">管理员信息设置</a></dd>
             <dd><a href="javascript:;">图书馆信息设置</a></dd>
             <dd><a href="javascript:;">图书词库设置</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item">
          <a href="{{ url_for('main.search_book') }}">图书信息查询</a>
        </li>
        <li class="layui-nav-item">
          <a href="{{ url_for('main.search_student') }}">学生信息查询</a>
        </li>
      </ul>
    </div>
  </div>

  <div class="layui-body">
    <!-- 内容主体区域 -->
    <div class="layui-card layui-row layui-col-space10" style="margin:15px 10px;width:100%;">
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
        </div>
        {% endfor %}
        {% block card %}{% endblock %}
        <div class="layui-card-body">
        {% block body %}
        {% endblock %}
        </div>
    </div>
  </div>

  <div class="layui-footer">
    Copyright 2019 Construct&nbsp;&nbsp;|&nbsp;&nbsp;版权所有:信息162许致立
  </div>
</div>
<script src="../static/layui/layui.js"></script>
<script>

layui.use('element', function(){
  var element = layui.element;
  element.init();


});
</script>

{% block script %}

{% endblock %}

</body>
</html>

app/templates/main/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="../static/layui/css/layui.css">
    <style>{% block style %}{% endblock %}</style>
</head>
<body style="background-color:#f2f2f2;height:100%; width:100%;">
<script src="../static/layui/layui.js"></script>


<div class="layui-container">
<ul class="layui-nav layui-nav-tree layui-nav-side">
  <span style="color:#BFC0C2;font-size: medium;margin-left: 20px;line-height: 50px;">图书管理系统</span>
  <li class="layui-nav-item">
    <a href="javascript:;">图书管理</a>
    <dl class="layui-nav-child">
      <dd><a href="javascript:;">入库管理</a></dd>
      <dd><a href="javascript:;">学生借书</a></dd>
      <dd><a href="">学生还书</a></dd>
      <dd><a href="">图书注销</a></dd>
    </dl>
  </li>
  <li class="layui-nav-item">
    <a href="javascript:;">信息设置</a>
    <dl class="layui-nav-child">
      <dd><a href="">管理员设置</a></dd>
      <dd><a href="">图书馆信息设置</a></dd>
      <dd><a href="">图书词库设置</a></dd>
    </dl>
  </li>
  <li class="layui-nav-item">
    <a href="http://127.0.0.1:5000/search_book">图书信息查询</a>
  </li>
    <li class="layui-nav-item">
    <a href="javascript:;">学生信息查询</a>
  </li>
</ul>

<ul class="layui-nav" style="text-align:right;background-color:#FFFFFF;width:110%;">
  <li class="layui-nav-item">
    <a href="" style="color:#000000">个人中心<span class="layui-badge-dot"></span></a>
     <dl class="layui-nav-child">
      <dd><a href="javascript:;">修改信息</a></dd>
      <dd><a href="javascript:;">退出系统</a></dd>
    </dl>
  </li>
</ul>


<div class="layui-card layui-row layui-col-space10" style="margin:15px 100px;width:100%;">
    <div class="layui-card-header">{% block card %}{% endblock %}</div>
    <div class="layui-card-body" style="height:480px">
        {% block body %}
        {% endblock %}
    </div>
</div>

<script>
{% block script %}

{% endblock %}
</script>
</body>
</html>

app/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}首页{% endblock %}\
{% block head %}
    <script type="text/javascript" src="http://echarts.baidu.com/dist/echarts.js"></script>
{% endblock %}

{% block body %}
<div id="main" style="width: 900px;height:470px;"></div>

{% endblock %}
{% block script %}
    <script>
    var a = echarts;
    var myChart = a.init(document.getElementById('main'));
     // 显示标题，图例和空的坐标轴
     myChart.setOption({
         title: {
             text: '近10天借书还书人次汇总图'
         },
         tooltip : {
        trigger: 'axis'
        },
        legend: {
            data:['今日数据']
        },
        toolbox: {
            show : true,
            feature : {
                mark : {show: true},
                dataView : {show: true, readOnly: false},
                magicType : {show: true, type: ['line', 'bar']}
                // restore : {show: true},
                // saveAsImage : {show: true}
            }
        },
        calculable : true,

         xAxis : [
            {
                type : 'category',
                boundaryGap : false,
                data : []
            }
        ],
         yAxis : [
            {
                type : 'value',
                axisLabel : {
                    formatter: '{value}'
                }
            }
        ],
         series : [
            {
                name:'最多数量',
                type:'line',
                data:[],
                markPoint : {
                    data : [
                        {type : 'max', name: '最大值'},
                        {type : 'min', name: '最小值'}
                    ]
                },
                markLine : {
                    data : [
                        {type : 'average', name: '平均值'}
                    ]
                }
            }]
         });
         myChart.showLoading();    //数据加载完之前先显示一段简单的loading动画
         var names=[];    //名称数组（实际用来盛放X轴坐标值）
         var nums=[];    //数量数组（实际用来盛放Y坐标值）
         $.ajax({
         type : "get",
//       async : true,            //异步请求（同步请求将会锁住浏览器，用户其他操作必须等待请求完成才可以执行）
         url : "{{ url_for('main.echarts') }}",    //请求发送
         dataType : "json",        //返回数据形式为json
         success : function(data) {
             //请求成功时执行该函数内容，result即为服务器返回的json对象
             if (data) {
                for(var i=0;i<data.length;i++){
                   names.push(data[i]["name"]);    //挨个取出名称并填入类别数组
                   nums.push(data[i]["num"]);    //挨个取出数量并填入销量数组
                }
                myChart.hideLoading();    //隐藏加载动画
                myChart.setOption({        //加载数据图表
                    xAxis: {
                        data: names
                    },
                    series: [{
                        // 根据名字对应到相应的系列
                        name: '数量',
                        data: nums
                    }]
                });

             }

        },
         error : function(errorMsg) {
             //请求失败时执行该函数
             alert("图表请求数据失败!");
             myChart.hideLoading();
         }
    })
    </script>

{% endblock %}

app/templates/main/search-student.html
{% extends "main/base.html" %}
{% block title %}查询学生信息{% endblock %}

{% block card %}<div class="layui-card-header"><h2>查询学生信息</h2></div>{% endblock %}
{% block body %}
    <form class="layui-form" method="post" id="searchForm">
    <!--{{ form.csrf_token }}-->
        <div class="layui-form-item">
            <div class="layui-inline">
                <div class="layui-row layui-col-space10">
                    <div class="layui-col-md4">
                        <label style="font-size: medium;width: 180px;" class="layui-form-label">请输入学生借阅卡号码：</label>
                    </div>
                    <div class="layui-col-md5">
                        <div class="layui-input-inline">
                            {{ form.card(class="layui-input", id="card") }}
                        </div>
                    </div>
                    <div class="layui-col-md2">
                        <div class="layui-input-inline">{{ form.submit(class="layui-btn", id="search") }}</div>

                    </div>
                </div>
            </div>

        </div>
    </form>
    <div id="info">
    <p>
        <span>姓名：<span id="name"></span></span>
        <span style="margin-left: 140px;">性别：<span id="gender"></span></span>
        <span style="margin-left: 120px;">有效期至：<span id="valid_date"></span></span>
        <span style="margin-left: 140px;">是否欠费：<span id="debt"></span></span>
    </p>
    </div>
    <div id="remove">
    <table lay-even id="result" lay-filter="re">
      <thead>
        <tr>
          <th lay-data="{field:'barcode', width:160}">图书编号</th>
          <th lay-data="{field:'book_name', width:200}">书名</th>
          <th lay-data="{field:'author', width:140}">作者</th>
          <th lay-data="{field:'start_date', width:200}">起始日期</th>
          <th lay-data="{field:'due_date', width:200}">应还日期</th>
          <th lay-data="{field:'end_date'}">还书日期</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>
    </div>
    <table id="test" lay-filter="test"></table>

{% endblock %}

{% block script %}
    <script>
    layui.use(['form','table','jquery'], function(){
        var form = layui.form;
        var table = layui.table;
        var $ = layui.$;

        table.init('re', {
              height: 390
              ,limit: 7
              ,page: true
        });

        $(document).ready(function(){
            $('#search').on('click',function () {
                var form = new FormData(document.getElementById("searchForm"));
                if($('#card').val() === ""){
                    layui.use('layer', function(){
                        var layer = layui.layer;

                        layer.msg('请填写查询内容',{time: 800});
                    });
                }
                else{
                    $.ajax({
                        url:"{{ url_for('main.find_student') }}",
                        type:"post",
                        data:form,
                        processData:false,
                        contentType:false,
                        success:function(data){
                            $("#name").empty();
                            $("#gender").empty();
                            $("#valid_date").empty();
                            $("#debt").empty();
                            if(data.length !== 0){
                                $("#name").append(data[0].name);
                                $("#gender").append(data[0].gender);
                                $("#valid_date").append(data[0].valid_date);
                                if(data[0].debt === false){
                                    $("#debt").append('否');
                                }
                                else{
                                    $("#debt").append('是');
                                }

                                $.ajax({
                                    url:"{{ url_for('main.find_record') }}",
                                    type:"post",
                                    data:form,
                                    processData:false,
                                    contentType:false,
                                    success:function(data){
                                        if (data.length !== 0){
                                            $('#remove').remove();
                                            table.render({
                                                elem: '#test'
                                                ,data:data
                                                ,cols: [[
                                                    {field:'barcode', title:'图书编号', width:160}
                                                    ,{field:'book_name', title:'书名', width:200}
                                                    ,{field:'author', title:'作者', width:140}
                                                    ,{field:'start_date', title:'起始日期', width:200}
                                                    ,{field:'due_date', title:'应还日期', width:200}
                                                    ,{field:'end_date', title:'还书日期'}
                                                ]]
                                                ,page: true
                                                ,height: 390
                                                ,limit: 7
                                                ,response: {
                                                    statusCode: 200 //重新规定成功的状态码为 200，table 组件默认为 0
                                                }
                                                ,parseData: function(data){ //将原始数据解析成 table 组件所规定的数据
                                                    return {
                                                        "code": data.status, //解析接口状态
                                                        "msg": data.message, //解析提示文本
                                                        "count": data.total, //解析数据长度
                                                        "data": data.rows.item //解析数据列表
                                                    };
                                                }
                                            });
                                        }
                                        else{
                                            layui.use('layer', function(){
                                            var layer = layui.layer;

                                            layer.msg('没有任何借阅记录',{time: 1000});
                                            });
                                        }
                                    }
                                });

                            }
                            else {
                                layui.use('layer', function(){
                                var layer = layui.layer;

                                layer.msg('找不到该学生！',{time: 1000});
                                });
                            }
                        }
                    });

                }
                return false;
            });
        });
    });
    </script>
{% endblock %}